### PR TITLE
Add mouse wheel zooming to OrbitControls

### PR DESCRIPTION
**Pull request by alteous**
This completes https://github.com/kvark/three-rs/pull/59

### CODE REVIEW

**Comment by kvark** [comment]
Thank you!
The merge commits indicate that you didn't rebase the original patch. Would you be able to rework the PR so that there is only 2 commits (original + your fixes)?

**Comment by alteous** [comment]
Yes, I'll have a go squashing the commits.

**Comment by kvark** [comment]
A little warning: I'm not a git guru, but last time I tried squashing a merge commit and a non-merge commit - didn't end well. It appears that Git treats merge commits in a special way, and squashing it with another one makes the result marked as a merge commit too.

**Comment by alteous** [comment]
Hold on... this is getting messy! :)

**Comment by vitvakatu** [comment]
In my opinion, it makes sense not to merge @bobgates' branch and simply rewrite all code in one commit. And then you can mention @bobgates in commit message. It will prevent a lot of pain.
@kvark ?

**Comment by alteous** [comment]
Did that work?

**Comment by vitvakatu** [comment]
Oh, well, it looks good

**Comment by kvark** [comment]
Thank you!
bors r+

**Pull request merged**
